WebApplication/Areas/Admin/Pages/Users/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication.Areas.Admin.Pages.Users
{
    public class DeleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApplication/Areas/Admin/Pages/Users/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication.Areas.Admin.Pages.Users
{
    public class DetailsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApplication/Areas/Admin/Pages/Users/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication.Areas.Admin.Pages.Users
{
    public class EditModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApplication/Pages/Payments/Payment.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Services;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Pages.Payments
{
    [Authorize]
    public class PaymentModel : PageModel
    {
        public const string DIRECT_PAYMENT = "Pay Directly";
        public const string DEEFAULT_STATUS = "PENDING";


        private readonly ICartDetailServices _cartDetailServices;
        private readonly IOrderServices _orderServices;
        private readonly UserManager<User> _userManager;

        public PaymentModel(ICartDetailServices cartDetailServices, IOrderServices orderServices, UserManager<User> userManager)
        {
            _cartDetailServices = cartDetailServices;
            _orderServices = orderServices;
            _userManager = userManager;
        }

        [BindProperty]
        public Order Order { get; set; }
        public CartDetail paymentCart { get; set; }
        public User userLoggedin { get; set; }
        public List<Voucher> Voucher { get; set; }

        public async Task<IActionResult> OnGet()
        {
            try
            {
                var paymentCartId = TempData["paymentCartId"] as int?;
                userLoggedin = await _userManager.GetUserAsync(User);
                paymentCart = await _cartDetailServices.GetAll().Include(p => p.Product).FirstOrDefaultAsync(c => c.CartDetailId == paymentCartId);
                TempData["paymentCart"] = paymentCart.CartDetailId;
            }
            catch (Exception e)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostPurchaseItemAsync()
        {
            var payCart = TempData["paymentCart"] as int?;
            paymentCart = await _cartDetailServices.GetAll().Where(c => c.CartDetailId == payCart).FirstOrDefaultAsync();
            if (paymentCart != null)
            {
                Order order = new Order();
                order.UserId = paymentCart.UserId;
                order.ProductId = paymentCart.ProductId;
                if (Order != null)
                {
                    order.DeliverMethod = Order.DeliverMethod;
                    order.DeliverDetais = Order.DeliverDetais;
                    order.PaymentDetais = Order.PaymentDetais;
                    order.Note = Order.Note;
                }
                else
                {
                    order.DeliverMethod = "Self-transport";
                    order.DeliverDetais = "Nothing";
                    order.PaymentDetais = "Nothing";
                }
                order.PaymentMethod = DIRECT_PAYMENT;
                order.OrderStatus = DEEFAULT_STATUS;

                await _orderServices.Create(order);
                await _cartDetailServices.Delete(paymentCart);
                return RedirectToPage("./PaymentSuccess");
            }
            return Page();
        }
        public async Task<IActionResult> OnPostUpdateStatusOderAsync()
        {
            return null;
        }
    }
}

WebApplication/Pages/Payments/PaymentSuccess.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication.Pages.Payment
{
    [Authorize]
    public class PaymentSuccessModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebApplication/Pages/Products/Cart.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Services;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Pages.Products
{
    [Authorize]
    public class CartModel : PageModel
    {
        private readonly ICartDetailServices _cartDetailServices;
        private readonly IUserServices _userServices;
        private readonly UserManager<User> _userManager;
        private readonly IProductServices _productServices;
        private readonly IOrderServices _orderServices;
        public CartModel(ICartDetailServices cartDetailServices, IUserServices userServices, UserManager<User> userManager, IProductServices productServices, IOrderServices orderServices)
        {
            _cartDetailServices = cartDetailServices;
            _userServices = userServices;
            _userManager = userManager;
            _productServices = productServices;
            _orderServices = orderServices;
        }

        [BindProperty]
        public CartDetail cartDetail { get; set; }

        public List<Product> RandomProduct { get; set; }
        public List<Product> listCartProduct { get; set; }
        public List<CartDetail> CartDetail { get; set; }
        [BindProperty]
        public string quantityUpdateAction { get; set; }
        [BindProperty]
        public int cartDetailId { get; set; }
        [BindProperty]
        public CartDetail DetailCart { get; set; }

        public List<Voucher> Voucher { get; set; }

        [BindProperty]
        public int paymentCart { get; set; }

        public string ErrorMessage { get; private set; }

        public async Task<IActionResult> OnGet()
        {
            // String currentUserId = _userManager.GetUserId(User);
            var userClaim = await _userManager.GetUserAsync(this.User);
            CartDetail = await _cartDetailServices.GetAll().Include(c => c.Product).Where(c => c.UserId == userClaim.Id).ToListAsync();
            User user = _userServices.FirstOrDefault(u => u.Id == userClaim.Id);
            listCartProduct = GetListProductInCart(CartDetail);
            RandomProduct = await _productServices.GetAll().ToListAsync();

            if (user.Vouchers == null)
            {
                return Page();
            }
            else
            {
                foreach (var voucher in user.Vouchers)
                {
                    Voucher.Add(voucher);
                }
            }


            return Page();
        }



        public List<Product> GetListProductInCart(List<CartDetail> listCart)
        {
            List<Product> listProduct = new List<Product>();
            foreach (CartDetail cartDetail in listCart)
            {
                listProduct.Add(cartDetail.Product);
            }
            return listProduct;
        }

        public async Task<IActionResult> OnPostUpdateQuantityAsync()
        {
            var action = Request.Form["action"];
            var cartId = Int64.Parse(Request.Form["cartId"]);
            var userClaim = await _userManager.GetUserAsync(this.User);
            User user = _userServices.FirstOrDefault(u => u.Id == userClaim.Id);
            var cartDetail = await _cartDetailServices.GetAll().Where(c => c.CartDetailId == cartId).FirstOrDefaultAsync();


            if (action.Equals("increase"))
            {
                cartDetail.Quantity++;
            }
            else
            {
                if (cartDetail == null || cartDetail.Quantity == 0)
                {
                    await _cartDetailServices.Delete(cartDetail);
                    CartDetail = await _cartDetailServices.GetAll().Include(c => c.Product).Where(c => c.UserId == userClaim.Id).ToListAsync();
                    listCartProduct = GetListProductInCart(CartDetail);
                    RandomProduct = await _productServices.GetAll().ToListAsync();
                    return Page();
                }
                cartDetail.Quantity--;
            }

            await _cartDetailServices.Update(cartDetail);
            int quantity = cartDetail.Quantity;
            return new JsonResult(new { quantity });
        }

        public async Task<IActionResult> OnPostPaymentAsync()
        {
            /* var cartData = await _cartDetailServices.GetAll().Where(c => c.CartDetailId == paymentCart).FirstOrDefaultAsync();
             if(paymentCart != null)
             {
                 Order order = new Order();
                 order.UserId = cartData.UserId;
                 order.ProductId = cartData.ProductId;
                 order.DeliverMethod = "Self-transport";
                 order.DeliverDetais = "Nothing";
                 order.PaymentMethod = "Pay directly";
                 order.PaymentDetais = "Nothing";
                 order.OrderStatus = "Preparing";

                 await _orderServices.Create(order);

                 return RedirectToPage("./Index");
             }*/
            TempData["paymentCartId"] = paymentCart;
            return RedirectToPage("/Payments/Payment");
        }

        public async void loadDataToPage()
        {
            var userClaim = await _userManager.GetUserAsync(this.User);
            CartDetail = await _cartDetailServices.GetAll().Where(c => c.UserId == userClaim.Id).ToListAsync();
            User user = _userServices.FirstOrDefault(u => u.Id == userClaim.Id);
            listCartProduct = GetListProductInCart(CartDetail);
            RandomProduct = await _productServices.GetAll().ToListAsync();
        }
    }
}

WebApplication/Pages/Products/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using BusinessObjects;
using Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Identity;
using Services.Interfaces;

namespace WebApplication.Pages.Products
{
    [Authorize(Roles = "Supplier")]
    public class CreateModel : PageModel
    {
        private readonly IProductServices _productServices;
        private readonly ICategoryServices _categoryServices;
        private readonly IUserServices _userServices;
        protected readonly UserManager<User> _userManager;

        public CreateModel(IProductServices productServices, ICategoryServices categoryServices, IUserServices userServices, UserManager<User> userManager)
        {
            _productServices = productServices;
            _categoryServices = categoryServices;
            _userServices = userServices;
            _userManager = userManager;
        }

        [BindProperty]
        public Product Product { get; set; }
        [BindProperty]
        public string ImageUrlsReview { get; set; }

        public async Task<IActionResult> OnGet()
        {
            string[] initialImages = { "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAMFBMVEXp7vG6vsG3u77s8fTCxsnn7O/f5OfFyczP09bM0dO8wMPk6ezY3eDd4uXR1tnJzdBvAX/cAAACVElEQVR4nO3b23KDIBRA0ShGU0n0//+2KmO94gWZ8Zxmr7fmwWEHJsJUHw8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwO1MHHdn+L3rIoK6eshsNJ8kTaJI07fERPOO1Nc1vgQm2oiBTWJ+d8+CqV1heplLzMRNonED+4mg7L6p591FC+133/xCRNCtd3nL9BlxWP++MOaXFdEXFjZ7r8D9l45C8y6aG0cWtP/SUGhs2d8dA/ZfGgrzYX+TVqcTNRRO9l+fS5eSYzQs85psUcuzk6igcLoHPz2J8gvzWaH/JLS+95RfOD8o1p5CU5R7l5LkfKEp0mQ1UX7hsVXqDpRrifILD/3S9CfmlUQFhQfuFu0STTyJ8gsP3PH7GVxN1FC4t2sbBy4TNRTu7LyHJbqaqKFw+/Q0ncFloo7CjRPwMnCWqKXQZ75El4nKC9dmcJaou9AXOE5UXbi+RGeJygrz8Uf+GewSn9uXuplnWDZJ7d8f24F/s6iq0LYf9olbS3Q8i5oKrRu4S9ybwaQ/aCkqtP3I28QDgeoK7TBya/aXqL5COx67PTCD2grtdOwH+pQV2r0a7YVBgZoKwwIVFQYG6ikMDVRTGByopjD8ATcKb0UhhRTe77sKs2DV7FKSjId18TUEBYVyLhUThWfILHTDqmI85/2RWWjcE/bhP6OD7maT3h20MHsA47JC3PsW0wcwLhv9t0OOPOIkCn21y2bXXwlyylxiYMPk1SuCSmpfK8bNQvIrpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwNX4BCbAju9/X67UAAAAASUVORK5CYII=" };
            string currentUserId =  _userManager.GetUserId(User);
            Product initialProduct = new Product();
            initialProduct.ProductName = "ProductName";
            initialProduct.SellPrice = 0;
            initialProduct.RentPrice = 0;
            initialProduct.ImageUrls = initialImages;
            initialProduct.UserId = currentUserId;

            ImageUrlsReview = string.Join(',', initialImages);
            Product = initialProduct;

            ViewData["CategoryId"] = new SelectList(await _categoryServices.GetAll().ToListAsync(), "CategoryId", "CategoryName");
           /* ViewData["UserId"] = new SelectList(await _userServices.GetAll().ToListAsync(), "Id", "Fullname");*/
            return Page();
        }


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostCreateAsync()
        {
            Product updateProduct = Product;
            updateProduct.ImageUrls = ImageUrlsReview.Split(',', StringSplitOptions.RemoveEmptyEntries);
            Product = updateProduct;

            if (!ModelState.IsValid)
            {
                return Page();
            }
            await _productServices.Create(Product);

            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostPreviewAsync()
        {
            Product updateProduct = Product;
            updateProduct.ImageUrls = ImageUrlsReview.Split(',', StringSplitOptions.RemoveEmptyEntries);
            Product = updateProduct;
            ViewData["CategoryId"] = new SelectList(await _categoryServices.GetAll().ToListAsync(), "CategoryId", "CategoryName");
            ViewData["UserId"] = new SelectList(await _userServices.GetAll().ToListAsync(), "Id", "Fullname");
            return Page();
        }
    }
}

WebApplication/Pages/Products/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BusinessObjects;
using Services;
using Microsoft.AspNetCore.Identity;
using System.Net.NetworkInformation;
using Services.Interfaces;

namespace WebApplication.Pages.Products
{
    public class DetailsModel : PageModel
    {
        private readonly IProductServices _productServices;
        private readonly ICartDetailServices _cartDetailServices;
        private readonly UserManager<User> _userManager;

        public DetailsModel(IProductServices productServices, ICartDetailServices cartDetailServices, UserManager<User> userManager)
        {
            _productServices = productServices;
            _cartDetailServices = cartDetailServices;
            _userManager = userManager;
        }

        public List<CartDetail> listUserCart { get; set; }

        [BindProperty]
        public CartDetail cartDetail { get; set; }
        public Product Product { get; set; }
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            //var user = _userManager.GetUserAsync(this.User);
            if (id == null)
            {
                return NotFound();
            }

            Product = await _productServices.GetAll().Include(p => p.Category).FirstOrDefaultAsync(m => m.ProductId == id);

            if (Product == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAddToCartAsync()
        {
            var user = await _userManager.GetUserAsync(this.User);
            try
            {
                listUserCart = await _cartDetailServices.GetAll().Where(c => c.UserId == user.Id).ToListAsync();
                    if (listUserCart != null)
                    {
                        var pro = listUserCart.Where(u => u.ProductId == cartDetail.ProductId).FirstOrDefault();
                        if (pro != null)
                        {
                            pro.Quantity++;
                            await _cartDetailServices.Update(pro);
                        //Reload data from database 

                        return RedirectToPage("./Cart");
                    }
                    }
                    cartDetail.UserId = user.Id;
                    cartDetail.Quantity = 1;
                    await _cartDetailServices.Create(cartDetail);
            }
            catch (Exception e)
            {
                return RedirectToPage("/Index");
            }
            return RedirectToPage("./Cart");
        }
    }
}

WebApplication/Pages/Products/Cart.cshtml
@page "/Cart"
@model WebApplication.Pages.Products.CartModel

@{
    ViewData["Title"] = "Cart";
}
<style>
    .table-wrapper {
        height: 300px;
        overflow-y: scroll;
    }

        .table-wrapper::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.1);
            background-color: #F5F5F5;
            border-radius: 10px;
        }

        .table-wrapper::-webkit-scrollbar {
            width: 10px;
            background-color: #F5F5F5;
        }

        .table-wrapper::-webkit-scrollbar-thumb {
            border-radius: 10px;
            background-color: #FFF;
            background-image: -webkit-gradient(linear, 40% 0%, 75% 84%, from(#4D9C41), to(#19911D), color-stop(.6, #54DE5D))
        }
</style>

<body>
    @Html.AntiForgeryToken()
    <div class="container h-100 w-100 mt-4 position-relative">
        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <span class="error-message position-absolute alert alert-danger w-100" role="alert">@Model.ErrorMessage</span>
        }
        <div class="row p-3" style="border-bottom: 2px solid #c1c1c1;">
            <div class="col-12 d-flex align-items-center ">
                <div class="col-6 navigate_wrapper text-left">
                    <i class="fas fa-backward ms-4" style="font-size:15px;"></i>
                    <a href="#" class="naviagate_link fw-bold ms-2">Continue shopping</a>
                </div>
                <div class="col-6 navigate_wrapper text-center ">
                    <p class="fw-bold fs-4">IWardrobe Cart</p>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="table-wrapper col-12">
                <table class="table position-relative">
                    <thead class="position-sticky z-3">
                        <tr class="mb-5">
                            <th scope="col" class="fs-5 text-center">@Html.DisplayNameFor(model => model.CartDetail[0].Product.ProductName)</th>
                            <th scope="col" class="fs-5 text-center">@Html.DisplayNameFor(model => model.CartDetail[0].Product.ImageUrls)</th>
                            <th scope="col" class="fs-5 text-center">@Html.DisplayNameFor(model => model.CartDetail[0].Quantity)</th>
                            <th scope="col" class="fs-5 text-center">Product's price per unit'</th>
                            <th scope="col" class="fs-5 text-center">Pick to pay</th>
                        </tr>
                    </thead>
                    <tbody class="table-body h-50 ">
                        @if (Model.CartDetail == null || Model.CartDetail.Count == 0)
                        {
                            <tr class="table-row mt-4 ">
                                <h2 class="text-black-50 text-center">Your cart is emmpty</h2>
                            </tr>
                        }
                        else
                        {
                            @foreach (var cart in Model.CartDetail)
                            {
                                <tr class="table-row mt-4 " data-cart="@cart.CartDetailId">
                                    <td class="fs-5 text-center align-middle res">@Html.DisplayFor(model => cart.Product.ProductName)</td>
                                    <td class="product-image text-center align-middle">
                                        <img src=@cart.Product.ImageUrls[0]
                                     alt="" class="rounded-3 img-fluid w-25">
                                    </td>
                                    <td class="fs-5 text-center align-middle">
                                        <div class="quantity-wrapper d-flex justify-content-between align-items-center m-auto">
                                            <button class="decrease-btn btn btn-adjustment fs-1" asp-page-handler="UpdateQuantity" data-action="decrease" data-cartid="@cart.CartDetailId">-</button>
                                            <h5 class="fw-normal mb-0 amount">@Html.DisplayFor(model => cart.Quantity)</h5>
                                            <button class="increase-btn btn btn-adjustment  fs-2" asp-page-handler="UpdateQuantity" data-action="increase" data-cartid="@cart.CartDetailId">+</button>
                                        </div>
                                    </td>
                                    <td class="fs-5 text-center align-middle price">@Html.DisplayFor(model => cart.Product.SellPrice)</td>

                                    <td class="fs-5 text-center align-middle">
                                        <input type="checkbox" name="" id="" class="w-100 product-pick">
                                        <span style="display:none" class="cartIdhidden">@Html.DisplayFor(model => cart.CartDetailId)</span>
                                    </td>
                                </tr>
                            }
                        }

                    </tbody>
                </table>
            </div>
            <div class="btn-wrapper ">
                <form method="post" asp-action="Payment" class="w-100 d-flex justify-content-center">
                    <input type="hidden" class="cartId" asp-for="@Model.paymentCart">
                    <button type="submit" disabled class="btn  w-25 align-self-center m-5 fw-bold btn-purchase" asp-page-handler="Payment">
                        <i class="fas fa-shopping-cart "></i>
                        <span class="btn-content">Purchase</span>
                    </button>
                </form>
            </div>
        </div>
        <div class="row d-flex justify-content-center align-items-center">
            <div class="recommend-wrapper col-12 d-flex m-auto  p-3 flex-wrap ">
                @if (Model.RandomProduct != null)
                {
                    @for (int i = Model.RandomProduct.Count() - 4; i < Model.RandomProduct.Count; i++)
                    {
                        <div class="product-wrapper text-center m-auto  h-50 col-lg-3 col-sm-6 col-md-4 col-xs-12 p-1">
                            <div class="image--wrapper">
                                <img src="@Html.DisplayFor(model => Model.RandomProduct[i].ImageUrls)"
                             alt="" class="rounded-top-4 w-75">
                            </div>
                            <div class="product-infor w-75 m-auto text-center rounded-bottom-4"
                         style="background-color: #dddedb; padding-bottom: 10px;">
                                <span class="product__name fs-4 d-block " style="white-space: nowrap;  text-overflow: ellipsis;overflow: hidden;"> @Html.DisplayFor(model => Model.RandomProduct[i].ProductName)</span>
                                <button class="btn btn-success w-50 d-block fw-bold" style="margin:auto" type="button">
                                    <a asp-page="/Products/Details" asp-route-id="@Model.RandomProduct[i].ProductId" style=" text-decoration:none; color:#fff">View detail</a>
                                </button>
                            </div>
                        </div>
                    }
                }

            </div>
        </div>
    </div>
</body>
@section Scripts{
    <script>
        $(document).ready(function () {
            $('.decrease-btn, .increase-btn').click(function () {
                var action = $(this).data('action');
                var cartId = $(this).data('cartid');
                var cart = $(this).closest('.table-row').data('cart');
                contentType: 'application/json',
                    $.ajax({
                        type: 'Post',
                        url: '/Cart?handler=UpdateQuantity',
                        data: {
                            action: action,
                            cartId: cartId,
                        },
                        headers: {
                            RequestVerificationToken:
                                $('input:hidden[name="__RequestVerificationToken"]').val()
                        },
                        success: function (res) {
                            if (res.quantity > 0 && res.quantity != 0) {
                                var amountItem = $(`[data-cart="${cart}"] .amount`)
                                amountItem.text(res.quantity);
                                console.log('Success');
                                console.log(res.quantity);
                            }
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    })
            })
        })
    </script>
}
    <script src="~/js/Cart.js"></script>
    <script src="https://code.jquery.com/jquery-4.3.1.min.js"></script>

WebApplication/Pages/Products/Delete.cshtml
@page "/products/delete"
@model WebApplication.Pages.Products.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ImageUrls)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ImageUrls)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.SellPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.SellPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.RentPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.RentPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.CreationDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.CreationDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Category.CategoryName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.User)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.User.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.IsDeleted)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.IsDeleted)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Product.ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>