WebApplication/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication/Pages/Home.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Services;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Data;

namespace WebApplication.Pages
{
    public class HomeModel : PageModel
    {
        private readonly IProductServices _productServices;
        private readonly IConfiguration Configuration;

        public HomeModel(IProductServices productServices, IConfiguration configuration)
        {
            _productServices = productServices;
            Configuration = configuration;
        }

        public PaginatedList<Product> Products { get; set; }
        public string CurrentFilter { get; set; }

        public async Task OnGetAsync(string searchString, string currentFilter, int? pageIndex)
        {
            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            CurrentFilter = searchString;

            IQueryable<Product> productsIQ = _productServices.GetAll();

            if (!String.IsNullOrEmpty(searchString))
            {
                productsIQ = productsIQ.Where(s => s.ProductName.Contains(searchString));
            }

            var pageSize = Configuration.GetValue("PageSize", 1);
            Products = await PaginatedList<Product>.CreateAsync(
                productsIQ.AsNoTracking(), pageIndex ?? 1, pageSize);
        }
    }
}

WebApplication/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services;
using System.Threading.Tasks;
using System;
using BusinessObjects;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;
using Microsoft.AspNetCore.Authentication;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using System.Linq;
using Services.Interfaces;

namespace WebApplication.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IUserServices _userServices;
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;

        public IndexModel(IUserServices userServices, SignInManager<User> signInManager, UserManager<User> userManager)
        {
            _userServices = userServices;
            _signInManager = signInManager;
            _userManager = userManager;
        }


        public class InputSignInModel
        {
            [Display(Name = "Email/Phone number")]
            public string EmailOrPhoneNumber { get; set; }

            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public class InputSignUpModel
        {
            [Required(ErrorMessage = "Fullname is required.")]
            [DataType("nvarchar")]
            [StringLength(50, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 1)]
            [Display(Name = "Fullname")]
            public string Fullname { get; set; }

            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [DataType(DataType.PhoneNumber)]
            [Display(Name = "Phone number")]
            public string PhoneNumber { get; set; }

            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        [BindProperty]
        public InputSignInModel SignInUser { get; set; }

        [BindProperty]
        public InputSignUpModel SignUpUser { get; set; }

        [BindProperty]
        public string ErrorSignIn { get; set; }

        [BindProperty]
        public string ErrorSignUp { get; set; }

        public bool IsSignUp { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }
        public string ReturnUrl { get; set; }

        public async Task<IActionResult> OnGetAsync(string type, string returnUrl = null)

        {
            returnUrl ??= Url.Content("~/home");
            if (_signInManager.IsSignedIn(User))
            {
                return LocalRedirect(returnUrl);
            }

            if (!string.IsNullOrEmpty(ErrorSignIn))
            {
                ModelState.AddModelError(string.Empty, ErrorSignIn);
            }
            IsSignUp = false;

            if (type != null)
            {
                if (type.ToLower().Equals("signup"))
                {
                    IsSignUp = true;
                }
            }

            returnUrl ??= Url.Content("~/home");

            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ReturnUrl = returnUrl;
            return Page();
        }

        public async Task<IActionResult> OnPostSignInAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/home");

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            var result = await _signInManager.PasswordSignInAsync(SignInUser.EmailOrPhoneNumber, SignInUser.Password, SignInUser.RememberMe, lockoutOnFailure: false);

            if (!result.Succeeded)
            {
                var user = _userServices.FirstOrDefault(u => u.PhoneNumber == SignInUser.EmailOrPhoneNumber);
                if (user != null)
                {
                    result = await _signInManager.PasswordSignInAsync(user.UserName, SignInUser.Password, SignInUser.RememberMe, lockoutOnFailure: false);
                }
            }

            if (result.Succeeded)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                ErrorSignIn = "Invalid sign in attempt.";
                IsSignUp = false;
                return Page();
            }
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/home");
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            var user = new User { Fullname = SignUpUser.Fullname, Email = SignUpUser.Email, PhoneNumber = SignUpUser.PhoneNumber, UserName = SignUpUser.Email };
            var result = await _userManager.CreateAsync(user, SignUpUser.Password);
            if (result.Succeeded)
            {
                var resultRole = await _userManager.AddToRolesAsync(user, new string[] { "Customer" });
                await _signInManager.SignInAsync(user, isPersistent: false);
                return LocalRedirect(returnUrl);
            }

            ErrorSignUp = "Invalid sign up attempt.";
            IsSignUp = true;
            return Page();
        }
    }
}

WebApplication/Pages/PaymentCart.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Services;
using Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Pages
{
    public class PaymentCartModel : PageModel
    {
        private readonly ICartDetailServices _cartDetailServices;
        private readonly IUserServices _userServices;

        public PaymentCartModel(ICartDetailServices cartDetailServices, IUserServices userServices)
        {
            _cartDetailServices = cartDetailServices;
            _userServices = userServices;
        }

        public Product Product { get; set; }
        public List<CartDetail> CartDetail { get; set; }

        public List<Voucher> Voucher { get; set; }
        public async Task<IActionResult> OnGet(string? id,string? username)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                CartDetail = await _cartDetailServices.GetAll().Where(c => c.UserId == id).ToListAsync();
                User user = _userServices.FirstOrDefault(u => u.UserName == username);

                foreach (var voucher in user.Vouchers)
                {
                    Voucher.Add(voucher);
                }
            }
            return Page();
        }
        public async Task<IActionResult> OnPostRemoveItemFromCart(int? id)
        {
            var productRemove = CartDetail.FirstOrDefault(c => c.ProductId == id);
            if(productRemove != null)
            {
                CartDetail.Remove(productRemove);
            }

            return Page(); 
        }
        
    }
}

WebApplication/Pages/RegisterSeller.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Services;
using Services.Interfaces;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace WebApplication.Pages
{
    [Authorize()]
    public class RegisterSellerModel : PageModel
    {
        protected readonly UserManager<User> _userManager;
        protected readonly IUserServices _userServices;
        private readonly SignInManager<User> _signInManager;
        public RegisterSellerModel(UserManager<User> userManager, IUserServices userServices, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _userServices = userServices;
            _signInManager = signInManager;
        }

        public class InputModel
        {
            [Required(ErrorMessage = "Your wardrobe'brand is required!")]
            [Display(Name = "Your wardrobe'brand")]
            [StringLength(255, MinimumLength = 3, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.")]
            public string BrandName { get; set; }

            [Required(ErrorMessage = "Identification code is required!")]
            [Display(Name = "Identification code")]
            [RegularExpression("^[0-9]+$", ErrorMessage = "Only numeric characters are allowed.")]
            [StringLength(12, MinimumLength = 12, ErrorMessage = "The must be at 12 characters long.")]
            public string IdentificationCode { get; set; }

            [Required(ErrorMessage = "Phone number is required!")]
            [Display(Name = "Phone number")]
            [DataType(DataType.PhoneNumber)]
            public string PhoneNumner { get; set; }

            [Required(ErrorMessage = "Address is required!")]
            [Display(Name = "Address")]
            public string Address { get; set; }
        }
        [BindProperty]
        public InputModel Input { get; set; }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            string _userId = _userManager.GetUserId(User);
            if (_userId != null)
            {
                var user = _userServices.GetById(_userId);
                user.BrandName = Input.BrandName;
                user.Address = Input.Address;
                user.PhoneNumber = Input.PhoneNumner;
                user.IdentificationCode = Input.IdentificationCode;
                try
                {
                    await _userServices.Update(user);
                    var roles = await _userManager.GetRolesAsync(user);
                    if (!roles.Contains("Supplier"))
                    {
                        await _userManager.AddToRoleAsync(user, "Supplier");
                        await _signInManager.SignInAsync(user, isPersistent: false);
                    }
                    return RedirectToPage("./Home");
                }
                catch
                {
                    return Page();

                }
            }
            return Page();
        }
    }
}

WebApplication/Pages/Home.cshtml
@page "/home"
@model HomeModel
@{
    ViewData["Title"] = "Home page";
}

<style>
    .btnPagination {
        color: #152534;
    }

        .btnPagination:hover {
            color: #152534;
            background-color: #C0E862;
        }

    .cardTitle {
        line-height: 1.5rem;
        height: 3rem;
        overflow: hidden;
        display: -webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 2;
    }
</style>

<div class="container">
    <form asp-page="./Home" method="get">
        <div class="form-actions no-color row">
            <div class="mx-auto mb-4 col-12 col-md-8 col-xl-6">
                <div class="input-group border rounded-3">
                    <input class="form-control searchInput" style="border: none;" type="search" placeholder="Seach product..." name="SearchString" value="@Model.CurrentFilter">
                    <span class="input-group-append" style="margin-left: unset;">
                        <button class="btn" style="background-color:#C0E862;" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
        </div>
    </form>

    <div class="row row-cols-1 row-cols-md-2 row-cols-xl-4 gy-4 d-flex justify-content-center justify-content-lg-start">
        @foreach (var item in Model.Products)
        {
            <div class="col d-flex align-items-center justify-content-center">
                <div class="card rounded-4 p-3 position-relative" style="width: 16rem;">
                    <img class="rounded-4 card-img-top" style="min-width: 14rem; min-height: 14rem;"
                         src=@item.ImageUrls[0]
                         alt="..." loading="lazy">
                    <div class="card-body pt-3 p-0">
                        <p class="fs-6 card-subtitle" style="color: #A1A1A1;">lxdfasion</p>
                        <p class="fs-5 fw-bold card-title cardTitle">@item.ProductName</p>
                        <div class="d-flex justify-content-between">
                            <div>
                                <span style="font-size: 14px;"><i class="fa-solid fa-dollar-sign"></i>&nbsp;Buy </span>
                                <p class="fs-6 fw-bold mb-1" style="color: #C0E862;">@string.Format("{0:#.000}", Convert.ToDecimal(item.SellPrice) / 1000) (đ)</p>
                            </div>
                            <div style="text-align: end;">
                                <span style="font-size: 14px"><i class="fa fa-retweet" aria-hidden="true"></i>&nbsp;Rent </span>
                                <p class="fs-6 fw-bold mb-1" style="color: #C0E862;">@string.Format("{0:#.000}", Convert.ToDecimal(item.RentPrice) / 1000) (đ)</p>
                            </div>
                        </div>
                        <a asp-page="/Products/Details" asp-route-id="@item.ProductId"
                           style="background-color:#C0E862;"
                           type="button"
                           class="btn btn-sm w-100">
                            <i class="fa fa-eye" aria-hidden="true"></i>
                            &nbsp;View Details
                        </a>
                    </div>
                    <button class="rounded-circle d-flex align-items-center justify-content-center btn btn-outline-danger position-absolute"
                            style="width: 32px; height: 32px; border: none; right: 1.5rem; top: 1.5rem;">
                        <i class="fa-solid fa-heart"></i>
                    </button>
                </div>
            </div>
        }

    </div>
    @{
        var prevDisabled = !Model.Products.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.Products.HasNextPage ? "disabled" : "";
    }
    <div class="d-flex align-items-center justify-content-center mt-4">
        <a asp-page="./Home"
           asp-route-pageIndex="@(Model.Products.PageIndex - 1)"
           class="btnPagination btn btn-outline-secondary btn-sm @prevDisabled"
           style="width: 100px;border: none;">
            <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
            &nbsp;Previous
        </a>
        <a asp-page="./Home"
           asp-route-pageIndex="@(Model.Products.PageIndex + 1)"
           class="btnPagination btn btn-outline-secondary btn-sm @nextDisabled"
           style="width: 100px;border: none;">
            Next&nbsp;
            <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
        </a>
    </div>
</div>

WebApplication/Pages/Index.cshtml
@page "/{type?}"
@model WebApplication.Pages.IndexModel
@{
    Layout = "_AuthLayout";
}

@{
    string signUpClass = Model.IsSignUp ? "right-panel-active" : "";
}

<div class="auth__container @signUpClass" id="container">
    <div class="form-container sign-up-container">
        <h1 style="font-weight: bold; color: #C0E862;">Create Account</h1>
        <form id="external-account" asp-area="Identity" asp-page="/Account/ExternalLogin" asp-route-returnUrl="@Model.ReturnUrl" method="post">
            <ul class="social-menu my-4">
                <li>
                    <button type="submit" name="provider" value="Facebook" title="Log in using your facebook account">
                        <i class="fa-brands fa-facebook-f"></i>
                    </button>
                </li>
                <li>
                    <button type="submit" name="provider" value="Google" title="Log in using your google account">
                        <i class="fa-brands fa-google"></i>
                    </button>
                </li>
                <li><button><i class="fa fa-phone" aria-hidden="true"></i></button></li>
            </ul>
        </form>
        <span>or use your email for registration</span>
        <form method="post" asp-route-returnUrl="@Model.ReturnUrl" asp-page-handler="SignUp" class="w-75 text-center">
            <div class="form-floating w-100 mb-3 mt-1">
                <input asp-for="SignUpUser.Fullname" class="form-control" required>
                <label for="floatingPassword">Your name</label>
            </div>
            <div class="form-floating w-100 mb-3">
                <input asp-for="SignUpUser.Email" class="form-control" required>
                <label for="floatingPassword">Your email</label>
            </div>
            <div class="form-floating w-100 mb-3">
                <input asp-for="SignUpUser.Password" class="form-control" required>
                <label for="floatingPassword">Password</label>
            </div>
            <div class="form-floating w-100">
                <input asp-for="SignUpUser.ConfirmPassword" class="form-control" required>
                <label for="floatingPassword">Confirm password</label>
            </div>
            <button type="submit" asp-page-handler="SignUp" asp-page="Index"
                    style="font-size: 1rem; font-weight: bold; padding: 12px 45px; background-color: #C0E862; color: white;"
                    class="btn btn-lg mt-4">
                Sign Up
            </button>
            <span style="position: absolute; bottom: 8px; left: 50%; transform: translateX(-50%);" class="text-danger">@Model.ErrorSignUp</span>
        </form>
    </div>
    <div class="form-container sign-in-container">
        <h1 style="font-weight: bold;  color: #C0E862;">Sign in</h1>
        <form id="external-account" asp-area="Identity" asp-page="./Account/ExternalLogin" asp-route-returnUrl="@Model.ReturnUrl" method="post">
            <ul class="social-menu my-4">
                <li>
                    <button type="submit" name="provider" value="Facebook" title="Log in using your facebook account">
                        <i class="fa-brands fa-facebook-f"></i>
                    </button>
                </li>
                <li>
                    <button type="submit" name="provider" value="Google" title="Log in using your google account">
                        <i class="fa-brands fa-google"></i>
                    </button>
                </li>
                <li><button><i class="fa fa-phone" aria-hidden="true"></i></button></li>
            </ul>
        </form>
        <span class="text-center">or use your account</span>
        <form asp-route-returnUrl="@Model.ReturnUrl" asp-page-handler="SignIn" method="post" class="w-75 text-center">
            <div class="form-floating w-100 mb-3 mt-1">
                <input asp-for="SignInUser.EmailOrPhoneNumber" class="form-control" required>
                <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating w-100">
                <input asp-for="SignInUser.Password" type="password" class="form-control" required>
                <label for="floatingPassword">Password</label>
            </div>
            <div class="d-flex align-items-center justify-content-between w-100 mt-2">
                <div>
                    <input type="checkbox" asp-for="SignInUser.RememberMe" />
                    <label class="form-check-label" for="flexCheckChecked">
                        Keep me signed in
                    </label>
                </div>
                <a asp-area="Identity" asp-page="/Account/ForgotPassword" class="text-decoration-none" style="color: #C0E862;">Forgot your password?</a>
            </div>
            <button type="submit"
                    style="font-size: 1rem; font-weight: bold; padding: 12px 45px; background-color: #C0E862; color: white;"
                    class="btn btn-lg mt-4">
                Sign In
            </button>
            <span style="position: absolute; bottom: 8px; left: 50%; transform: translateX(-50%);" class="text-danger">@Model.ErrorSignIn</span>
        </form>
    </div>
    <div class="overlay-container" id="overlayCon">
        <div class="overlay">
            <div class="overlay-panel overlay-left">
                <div class="overlay__content">
                    <img src="~/img/logo-horizontal.png" height="50px" />
                    <h1>Welcome Back!</h1>
                    <p>To keep connected with us please login with your personal info</p>
                    <button class="btn btn-lg mb-2" style="color: #C0E862; font-size: 1rem; font-weight: bold;">
                        SIGN
                        IN
                    </button>
                </div>

            </div>
            <div class="overlay-panel overlay-right">
                <div class="overlay__content">
                    <img src="~/img/logo-horizontal.png" height="50px" />
                    <h1>Hello, Friend!</h1>
                    <p>Enter your personal details and start journey with us</p>
                    <button class="btn btn-lg mb-2" style="color: #C0E862; font-size: 1rem; font-weight: bold;">
                        SIGN
                        UP
                    </button>
                </div>
            </div>
        </div>
        <button id="overlayBtn"></button>
    </div>
</div>


@*@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}*@

<script>
    const container = document.getElementById('container');
    const overlayCon = document.getElementById('overlayCon');
    const overlayBtn = document.getElementById('overlayBtn');
    overlayBtn.addEventListener('click', () => {
        container.classList.toggle('right-panel-active');

        overlayBtn.classList.remove('btnScaled');
        window.requestAnimationFrame(() => {
            overlayBtn.classList.add('btnScaled');
        })
    });
</script>

<style>
    .auth__container {
        position: relative;
        width: 1040px;
        height: 610px;
        background-color: #FFF;
        box-shadow: rgba(21, 37, 52, 0.3) 0px 10px 50px;
        border-radius: 13px;
        overflow: hidden;
    }

    .form-container {
        position: absolute;
        width: 60%;
        height: 100%;
        padding: 0px 40px;
        transition: all 0.6s ease-in-out;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .sign-up-container {
        opacity: 0;
        z-index: 1;
    }

    .sign-in-container {
        z-index: 2;
    }

    .social-menu {
        padding: 0;
        margin: 0;
        display: flex;
    }

        .social-menu li {
            list-style: none;
            margin: 0 10px;
        }

            .social-menu li .fa-brands {
                color: #152534;
                font-size: 18px;
                line-height: 40px;
                transition: .5s;
                cursor: pointer;
            }

            .social-menu li .fa {
                color: #152534;
                font-size: 18px;
                line-height: 40px;
                transition: .5s;
            }

            .social-menu li .fa-brands:hover {
                color: #FFF;
            }

            .social-menu li .fa:hover {
                color: #FFF;
            }

            .social-menu li button {
                position: relative;
                display: block;
                width: 40px;
                height: 40px;
                border-radius: 50%;
                background-color: white;
                text-align: center;
                transition: 0.5s;
                transform: translate(0, 0px);
                box-shadow: rgba(0, 0, 0, 0.16) 0px 10px 36px 0px, rgba(0, 0, 0, 0.06) 0px 0px 0px 1px;
                border: none;
            }

                .social-menu li button:hover {
                    color: #FFF;
                    transform: rotate(0deg) skew(0deg) translate(0, -10px);
                    box-shadow: rgba(0, 0, 0, 0.07) 0px 1px 2px, rgba(0, 0, 0, 0.07) 0px 2px 4px, rgba(0, 0, 0, 0.07) 0px 4px 8px, rgba(0, 0, 0, 0.07) 0px 8px 16px, rgba(0, 0, 0, 0.07) 0px 16px 32px, rgba(0, 0, 0, 0.07) 0px 32px 64px;
                }

            .social-menu li:nth-child(1) button:hover {
                background-color: #3b5999;
            }

            .social-menu li:nth-child(2) button:hover {
                background-color: #DB4437;
            }

            .social-menu li:nth-child(3) button:hover {
                background-color: #0F9D58;
            }

    .overlay-container {
        position: absolute;
        top: 0;
        left: 60%;
        width: 40%;
        height: 100%;
        overflow: hidden;
        transition: transform 0.6s ease-in-out;
        z-index: 9;
    }

    #overlayBtn {
        cursor: pointer;
        position: absolute;
        left: 50%;
        top: 360px;
        transform: translateX(-50%);
        width: 144.27px;
        height: 50px;
        border: 1px solid rgb(192, 232, 98);
        background: transparent;
        border-radius: 0.5rem;
    }

    .overlay {
        position: relative;
        color: #FFF;
        left: -150%;
        height: 100%;
        width: 250%;
        transition: transform 0.6s ease-in-out;
    }

    .overlay-panel {
        position: absolute;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        padding: 0px 40px;
        text-align: center;
        width: 416px;
        height: 610px;
        transition: 0.6s ease-in-out;
        background-image: url("/img/background_image_auth.png");
        background-color: #cccccc;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .overlay__content {
        background-color: rgb(0, 0, 0);
        background-color: rgba(0, 0, 0, 0.3);
        color: white;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        z-index: 2;
        width: 360px;
        padding: 16px;
        text-align: center;
    }

    .overlay-left {
        right: 60%;
        transform: translateX(-12%);
    }

    .overlay-right {
        right: 0;
        transform: translateX(0%);
    }

    .overlay-panel button {
        border: none;
        background-color: transparent;
    }

    .right-panel-active .overlay-container {
        transform: translateX(-150%);
    }

    .right-panel-active .overlay {
        transform: translateX(50%);
    }

    .right-panel-active .overlay-left {
        transform: translateX(25%);
    }

    .right-panel-active .overlay-right {
        transform: translateX(35%);
    }

    .right-panel-active .sign-in-container {
        transform: translateX(20%);
        opacity: 0;
    }

    .right-panel-active .sign-up-container {
        transform: translateX(66.7%);
        opacity: 1;
        z-index: 5;
        animation: show 0.6s;
    }

    @@keyframes show {

        0%,
        50% {
            opacity: 0;
            z-index: 1;
        }

        50.1%,
        100% {
            opacity: 1;
            z-index: 5;
        }
    }

    .btnScaled {
        animation: scaleBtn 0.6s;
    }

    @@keyframes scaleBtn {
        0% {
            width: 143.67px;
        }

        50% {
            width: 250px;
        }

        0% {
            width: 143.67px;
        }
    }
</style>
@*<a class="nav-link text-dark" asp-area="" asp-page="/Home">Home</a>*@